// <auto-generated />
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishWordSet.Migrations
{
    [DbContext(typeof(WordContext))]
    [Migration("20230219212528_lastEntryAdded")]
    partial class lastEntryAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lastEntry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("token")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Entities.Concrete.LearnedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("meaningWordSentence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("learnedWord_meanigSentence");

                    b.Property<string>("wordEnglish")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("learnedWord_word");

                    b.Property<string>("wordSentence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("learnedWord_sentence");

                    b.Property<string>("wordTurkish")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("learnedWord_meanig");

                    b.HasKey("Id");

                    b.HasIndex("wordEnglish")
                        .IsUnique()
                        .HasFilter("[learnedWord_word] IS NOT NULL");

                    b.ToTable("LearnedWords");
                });

            modelBuilder.Entity("Entities.Concrete.NWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turkish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
