//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishWordSet {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class SettingsFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsFile defaultInstance = ((SettingsFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsFile())));
        
        public static SettingsFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zbUIVrp4QpDLHjJjhV4gSE1lAniC20DXwQsDkMa68Ws")]
        public string UnsplashAPIKey {
            get {
                return ((string)(this["UnsplashAPIKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBTL7y3H--lfRrgzfFVsIPYjXs7f7TdkyU")]
        public string GoogleTranslateAPIKey {
            get {
                return ((string)(this["GoogleTranslateAPIKey"]));
            }
        }
    }
}
